version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Limit concurrency for dependabot PRs
    open-pull-requests-limit: 10
    reviewers:
      - "anupam19"
    assignees:
      - "anupam19"
